language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ptLo3KAh2GPQMSO16th/WPBOho4amBFsBwlcuN9o45m2M+sWLaADYQV7p9KU4Y1yZfg1oI2Pxv2zglOYRAwO3cwyNnn04RgnzG0uBw5NsLAt40hzLb19abyjivzyS+dwvlOVQRaFIw+v/jZbLc2VWClrvIQ03/pcQL8gxAdxQZkV43S1zdvc+9DUed8urgP+s/Wm/ZtePjl2XlVUWuT9WJXf5zJ4StITjCDvdO9OPl2Ds3r1G9Gf3/3r6Zl6Y7DpizK4alm82euWdGOOp5p3O0LM69heDPPr+3rytPgcgGSaLe91IlgmEln9wMz1txDAyIpuOqXFAbSPsZcEk7AuTsDBy5Goqnrcf8D3hEkyPteFl9celltNKKpjM2alWFENcDgyoE9LZBXEb+AjO8ZXrv//1Rp5q8vgBNEMvq0uzKkYXCNBxtmqInoq8K/aZnN2hJaF/439QdABYuYyhoWfHmNCESEryEGFw6wzodgfe+EkWA3Bm3qbjNPJVeQTzB3yswBtgR8dFvEvDyvOzB95X/6W3LE4OwpXZLXQRUnVSjaB727ZQDDCkZsrpHzQiTL7eWgy+heonpOSw/6+ToCYP/5MaQcp5VxrvfBon6Q9dGzkFR8HdstQutBM7oaxkB0CeWMJA3PkNcbPdUYlllbpgkM8A7UbsrOnG1QaqbMUBow=
  app: aviaj-backend-travis
  on:
    repo: TimeEscaper/aviaj-09-2016
    branches:
        only:
	- master
